with-expecter: True
packages:
  github.com/Yousef-Hammar/go-code-review/coupon_service/internal/service:
    config:
      all: True
      recursive: True
      mockname: "{{.InterfaceName}}"
      filename: "{{.InterfaceName | lower }}_mock.go"
      dir: "internal/service/internal/mocks"
      outpkg: "mocks"